---
title: "Gov 50 Final Project"
author: "Bolin Shen"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---

## Project Proposal

Does access to information/news increase the chances of political uprising? In this project, I want to examine the extent to which citizens' access to information and outside news (through channels like radio, newspapers, and television) leads to a greater likelihood of citizen uprising (for example riots and revolutions). I hypothesize that there is a positive correlation between access to information and likelihood of uprising: the less access citizens have to outside news and freedom of information, the less likely there will be grassroots uprisings against incumbent regimes; vice versa, the more access citizens have to information and news, the more likely they will be to rebel against the established governance. Traditional modernization theory from political theorists like Daniel Lerner and Seymour Martin Lipset place a huge emphasis on the dissemination of information to citizen, and argue that increased access to outside regimes and modes of governance as a result of globalization is likely to promote political thinking among grassroots. Along a similar line of thinking, I predict that a heightened sense of political awareness and understanding among the general populace is likely to lead to greater dissatisfaction with incumbent modes of governance and thus lead to expressions of dissatisfaction through political organization of riots and revolutions. 

I will use the political violence dataset, which is comprised of numerous measures for both access to information and political uprisings. My explanatory variables of interest summarizes access to information: TV access (Televisions per thousand population), radio access (Radios per thousand population), and newspaper access (Newspapers per capita). My outcome variables summarizes the chances/likelihood of political uprising: riots (any violent demonstration or clash of more than 100 citizens), revolutions (any illegal or forced change in the top governmental elite), anti-government demonstrations (any peaceful public gathering of at least 100 people). If I am able to observe greater occurrences of political uprisings with greater access to information and news, this would provide support for my hypothesis. On the other hand, if I observe less instances of political uprisings or the same level of political uprisings across levels of information access, this would provie evidence against my hypothesis. 




